version: "2"
services:
  thehive:
    image: thehiveproject/thehive4:latest
    ports:
      - "0.0.0.0:9000:9000"
    command:
      --cortex-port 9001
      --cortex-keys VpgDIi/gbo9O6LQJMO5r9gyaG+2jQBNA
    volumes:
      - ./test/vol/thehive/application.conf:/etc/thehive/application.conf
